### ISSUE TITLE
Multiple clients sync issue

### ISSUE THREAD

**Issue by luigi37** [abeauseigle/webSqlApp#1]
I started using the library with the attached example and it partially works.

Problem is that the local "id" must be unique apparently, otherwise the duplicated entries on the server do not get synched (only one gets).

If you have one client that's not an issue: client keeps track of local id, records insert by server have no id...

Problem is that if you have 2 clients, the local ids can cross and then one of the two items do not get populated.

Any workaround? I was thinking about regenerating the id every time the server version is download and putting at "set" operation an "id" which is not the local one but the MAX(id) on the server plus one...

**Comment by Peldano-pb** [comment]
Hi! Im using this example to make my app but i cant do a good sync with the server. Can i show you my code to both to see what im doing wrong?
