### ISSUE TITLE
Work in android?

### ISSUE THREAD

**Issue by danicarla** [abeauseigle/webSqlApp#6]
I can use in android?

**Comment by abeauseigle** [comment]
For sure, you can use it in Android. It doesn't depend on the operatin system, but on the browser (that support HTML5). On android, WebSQL is supported by Chrome(the best one), Opera, Safari and a lot more. Not supported by IE, and FF. You can use it also on iPhone, iPad, iOS, in Windows using HTML5.
UP+

**Comment by danicarla** [comment]
Tks :)
